# Generated by Django 6.0.3 on 2026-03-28 18:12

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_emprestimo',
            new_name='dataEmprestimo',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateField(default=biblioteca.models.devolucaoPadrao),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='maxRenovacoes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='renovacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
