# Generated by Django 6.0.3 on 2026-03-29 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_data_emprestimo_emprestimo_dataemprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
