# Generated by Django 6.0.3 on 2026-04-20 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alertalivrodisponivel'),
        ('biblioteca', '0004_usuario_id_autenticado_alertalivrodisponivel'),
    ]

    operations = [
    ]
