# Generated by Django 6.0.3 on 2026-05-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_merge_20260419_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
    ]
