[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd project && python manage.py collectstatic --noinput"]

[start]
cmd = "cd project && gunicorn project.wsgi"