name: Build and deploy Python app to Azure Web App - readme

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django check
        working-directory: ./project
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: |
          python manage.py check

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_36CEEF6FBB10469F8C314DE1C939606F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E3A0FF7F65494C74A76E3BDE9D4C0070 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_99E3F240E67A4B9DB052AE7E24A5B894 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'readme'
          slot-name: 'Production'
          package: ./project
