name: Build and deploy Python app to Azure Web App - readme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
                
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F609ADA283F442C0A9E5D3FB88BC8324 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3F1300FD2D54055AB48F57F56DFFE5C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_664D06C0BE794F12ACA096CCE92E97DF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'readme'
          slot-name: 'Production'
          package: ./project
          
